import Head from "next/head";
import React, { useState } from "react";
import Link from "next/link";
import Image from "next/image";
import Header from "../../components/header";
import Footer from "../../components/Footer";

export default function Login() {
  return (
    <>
      <Head>
        <title>Paramount Management Group</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="scroll-content">
        <section className="login">
          <div className="container">
            <div className="row justify-content-center">
              <div className="col-md-9">
                <div className="login-page">
                  <div className="row">
                    <div className="col-md-6">
                      <div className="login-left">
                        <h1>WELCOME TO</h1>
                        <img src="/images/login-logo.png" />
                        <Link href="">Login to Continue</Link>
                      </div>
                    </div>
                    <div className="col-md-6">
                      <div className="login-right">
                        <img src="/images/login-img.png" />
                        <form>
                          <input type="email" placeholder="Email" />
                          <input type="pasword" placeholder="Password" />
                          <div className="text-end">
                            <Link href="">Forgot your Password?</Link>
                          </div>
                          <div className="grad-bg">
                            <Link className="bgg" href="/dashboard">
                              Login
                            </Link>
                          </div>
                        </form>
                        <div className="text-center">
                          <h5>Don’t have any Account? <Link href="">Sign Up</Link></h5>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </>
  );
}
