import Head from "next/head";

import Link from "next/link";
import Image from "next/image";
import Header from "../../../components/header";
import Footer from "../../../components/Footer";

export default function ServiceDetail() {
  return (
    <>
      <Head>
        <title>Paramount Management Group</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="scroll-content">
        <Header />

        <section className="inner-banner blogs-banner servicedetail-banner">
          <div className="container">
            <div className="content">
              <h1 data-aos="fade-up" className="main-heading">
                <span>SERVICE DETAIL</span>
              </h1>
            </div>
          </div>
        </section>

        <section className="blog-detail-section-two service-detail-section-two">
          <div className="container">
            <div className="content">
              <div className="title text-center">
                <h6 data-aos="fade-up" className="mini-heading">
                  Paramount Management Group
                </h6>
                <h2 data-aos="fade-up" className="sub-heading">
                  Responsive <span>Maintenance & Repairs</span>
                </h2>
                <p data-aos="fade-up" className="paragraph">
                  At Paramount Management Group (PMG), we prioritize tenant
                  satisfaction through responsive, reliable{" "}
                  <b>property maintenance</b> services, ensuring seamless
                  operations and professional environments where businesses
                  thrive without unnecessary interruptions or concerns.
                </p>
              </div>

              <div className="row align-items-center mb-6">
                <div className="col-md-6">
                  <div className="img" data-aos="zoom-in">
                    <img src="/images/service-detail-section-two-img.png" />
                  </div>
                </div>

                <div className="col-md-6">
                  <div className="text">
                    <h5 className="sub-text">24/7 Maintenance Support</h5>
                    <p data-aos="fade-up" className="paragraph">
                      PMG provides tenants with immediate support, no matter the
                      time. Our <b>24/7 maintenance service </b> addresses
                      routine issues, urgent repairs, and unexpected challenges.
                      Whether it’s for <b>rental property maintenance</b> or{" "}
                      <b>commercial property maintenance services</b>, our team
                      ensures smooth, disruption-free operations and maintains
                      properties to the highest standards.
                    </p>
                    <h5 className="sub-text">Proactive Property Maintenance</h5>
                    <p data-aos="fade-up" className="paragraph">
                      Preventing problems before they occur is central to PMG’s{" "}
                      <b>property care management</b> approach. Regular
                      inspections, scheduled upkeep, and proactive improvements
                      keep properties in excellent condition. By reducing the
                      risk of major repairs, we create professional,
                      high-quality environments that meet both tenant and
                      property owner expectations.
                    </p>
                  </div>
                </div>
              </div>
              <div className="content">
                <div className="row">
                  <div className="col-md-4">
                    <h5 className="sub-text">Rapid Emergency Repairs</h5>
                    <p className="paragraph">
                      When emergencies arise, PMG acts swiftly to minimize
                      disruptions. From plumbing and electrical issues to urgent
                      structural fixes, our team prioritizes efficiency and
                      professionalism. Whether you need{" "}
                      <b>residential property maintenance</b> or emergency
                      solutions for <b>apartments,</b> our quick response
                      ensures tenant satisfaction and operational continuity.
                    </p>
                  </div>
                  <div className="col-md-4">
                    <h5 className="sub-text">Tenant-Focused Solutions</h5>
                    <p className="paragraph">
                      At PMG, tenant satisfaction is at the core of everything
                      we do. Clear communication, personalized service, and
                      attention to detail make our{" "}
                      <b>property management & maintenance</b> services reliable
                      and trusted.
                    </p>
                  </div>
                  <div className="col-md-4">
                    <h5 className="sub-text">Sustainable Practices</h5>
                    <p className="paragraph">
                      PMG incorporates eco-friendly materials and
                      energy-efficient solutions into our{" "}
                      <b>property maintenance services</b>. This reduces
                      environmental impact while supporting high-quality spaces
                      that are cost-effective and sustainable for the long term.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="home home-section-seven">
          <div className="container">
            <div className="title text-center">
              <h6 data-aos="fade-up" className="mini-heading">
                Paramount Management Group
              </h6>
              <h1 data-aos="fade-up" className="main-heading">
                Stay In <span>Touch</span>
              </h1>
              <p data-aos="fade-up" className="paragraph">
                It is a long established fact that a reader will be distracted
                by the readable content of a page when looking at its layout the
                point of using Lorem Ipsum.
              </p>
            </div>

            <div className="content">
              <div className="row justify-content-center">
                <div className="col-md-8">
                  <div className="row">
                    <div className="col-md-6">
                      <input type="text" placeholder="First Name" />
                    </div>

                    <div className="col-md-6">
                      <input type="text" placeholder="Last Name" />
                    </div>

                    <div className="col-md-6">
                      <input type="text" placeholder="First Name" />
                    </div>

                    <div className="col-md-6">
                      <input type="text" placeholder="Last Name" />
                    </div>

                    <div className="col-md-12">
                      <textarea placeholder="Message"></textarea>
                    </div>
                  </div>
                  <button>Send Message</button>
                </div>
              </div>
            </div>
          </div>
        </section>

        <Footer />
      </div>
    </>
  );
}
