"use client";
import Head from "next/head";

import Link from "next/link";
import Image from "next/image";
import Header from "../components/header";
import Footer from "../components/Footer";
import handleContactUs from "../auth/api/contactUsHelper";
import { useEffect, useState } from "react";
import axios from "@/utils/axios";

async function getProperties() {
  try {
    const response = await axios.get('/properties-show');
    console.log('API Response:', response); // Log full API response

    if (response?.data && Array.isArray(response.data)) {
      return response.data; // Return the array if correctly structured
    } else {
      console.error('Unexpected response format:', response.data);
      return []; // Return empty array if structure is unexpected
    }
  } catch (error) {
    console.error('Error fetching property from API:', error);
    throw error; // Propagate the error to the caller
  }
}


export default function Properties() {

  const [formData, setFormData] = useState({
    first_name: "",
    last_name: "",
    email: "",
    phone: "",
    message: "",
  });

  const handleInputChange = (field, value) => {
    setFormData({
      ...formData,
      [field]: value,
    });
  };

  const [properties, setProperties] = useState([]);
  const [isLoading, setIsLoading] = useState(true); // Loading state

  useEffect(() => {
    async function fetchData() {
      try {
        const fetchedProperties = await getProperties();
        console.log('Fetched Products:', fetchedProperties); // Log fetched products
        setProperties(Array.isArray(fetchedProperties) ? fetchedProperties : []); // Update state
      } catch (error) {
        console.error('Error fetching Properties:', error);
        setProperties([]); // Handle errors gracefully
      }
    }
    fetchData();
  }, []);


  return (
    <>
      <Head>
        <title>Paramount Management Group</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="scroll-content">
        <Header />

        <section className="inner-banner blogs-banner contact-banner">
          <div className="container">
            <div className="content">
              <h1 data-aos="fade-up" className="main-heading">
                <span>PROPERTIES</span>
              </h1>
            </div>
          </div>
        </section>

        <section className="home home-section-two properties-section-two">
          <div className="container">
            <div className="text-center title">
              <h6 data-aos="fade-up" className="mini-heading">
                Paramount Management Group
              </h6>
              <h1 data-aos="fade-up" className="main-heading">
                Find <span>Your Perfect Space</span>
              </h1>
              <p className="paragraph">
                Looking for an office that matches your ambition? Our featured
                office spaces are designed to help your business shine. Whether
                you're starting up or scaling up, discover the ideal backdrop
                for your next big move.
              </p>
            </div>

            <div className="row">
              {properties.length > 0 ? (
                properties.map((property) => (
                  <div className="col-md-6" key={property.id}>
                    <div className="inner" data-aos="zoom-in">
                      <div className="img">
                        <img
                          src="/images/home-sec-two-card-img1.png"
                          alt="home-sec-two-card-img1"
                        />
                      </div>
                      <div className="text">
                        <h5 className="sub-text">
                          {property.name}
                        </h5>
                        <p className="paragraph">
                          {property.address}
                        </p>
                        <div className="d-flex">
                          <div className="black-bg">
                            <h5 className="sub-text">
                              <Link href={`/property-details/${property.id}`}>
                                <span>View in Detail</span>
                              </Link>
                            </h5>
                          </div>
                          {/* <div>
                        <ul>
                          <li>790 SF | 1-5 Years | $22.78 /SF/YR</li>

                          <li>Office | Full Build-Out | Available Property</li>
                        </ul>
                      </div> */}
                        </div>
                      </div>
                    </div>
                  </div>

                ))
              ) : (
                <p>No products found in this category.</p>
              )}
            </div>
          </div>
        </section>

        <section className="home home-section-seven">
          <div className="container">
            <div className="title text-center">
              <h6 data-aos="fade-up" className="mini-heading">
                Paramount Management Group
              </h6>
              <h1 data-aos="fade-up" className="main-heading">
                Stay In <span>Touch</span>
              </h1>
              <p data-aos="fade-up" className="paragraph">
                We understand that finding the right commercial space is more
                than just finding an address. It's about finding a location that
                inspires, a space that supports your team's productivity, and a
                partner that understands your unique business needs.
              </p>
            </div>

            <div className="content">
              <div className="row justify-content-center">
                <div className="col-md-8">
                  <div className="row">
                    <div className="col-md-6">
                      <input
                        type="text"
                        placeholder="First Name *"
                        value={formData.first_name}
                        onChange={(e) => handleInputChange("first_name", e.target.value)}
                      />
                    </div>

                    <div className="col-md-6">
                      <input
                        type="text"
                        placeholder="Last Name *"
                        value={formData.last_name}
                        onChange={(e) => handleInputChange("last_name", e.target.value)}
                      />
                    </div>

                    <div className="col-md-6">
                      <input
                        type="email"
                        placeholder="Email Address *"
                        value={formData.email}
                        onChange={(e) => handleInputChange("email", e.target.value)}
                      />
                    </div>

                    <div className="col-md-6">
                      <input
                        type="tel"
                        placeholder="Phone Number *"
                        value={formData.phone}
                        onChange={(e) => handleInputChange("phone", e.target.value)}
                      />
                    </div>

                    <div className="col-md-12">
                      <textarea
                        placeholder="Message Here..."
                        value={formData.message}
                        onChange={(e) => handleInputChange("message", e.target.value)}
                      ></textarea>
                    </div>
                  </div>
                  <button onClick={() => handleContactUs(formData, setFormData)}>Send Message</button>
                </div>
              </div>
            </div>
          </div>
        </section>
        <Footer />
      </div>
    </>
  );
}
