import Head from "next/head";
import React, { useState } from "react";
import Link from "next/link";
import Image from "next/image";
import Header from "../../components/header";
import Footer from "../../components/Footer";

export default function Dashboard() {
  const [showModal, setShowModal] = useState(false);

  const handleOpenModal = () => setShowModal(true);
  const handleCloseModal = () => setShowModal(false);
  return (
    <>
      <Head>
        <title>Paramount Management Group</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="scroll-content">
        <section className="dashboard-main">
          <div className="container-fluid">
            <div className="dashboard-content d-flex">
              <div className="left-bar">
                <div className="top-logo">
                  <img src="/images/dashboard-logo.png" />
                </div>
                <div className="dashboard-buttons">
                  <ul>
                    <li>
                      <button className="active" id="dashboard">
                        <img src="/images/dash-icon.png" />
                        Dashboard
                      </button>
                    </li>

                    <li>
                      <button id="tickets">
                        <img src="/images/profile-icon.png" />
                        My Tickets
                      </button>
                    </li>

                    <li>
                      <Link href="/messages">
                        <button id="messages">
                          <img src="/images/msg-icon.png" />
                          Messages
                        </button>
                      </Link>
                    </li>

                    <li>
                      <button id="setting">
                        <img src="/images/setting-icon.png" />
                        Setting
                      </button>
                    </li>

                    <li>
                      <Link href="/login">
                        <button id="logout">
                          <img src="/images/logout-icon.png" />
                          Log Out
                        </button>
                      </Link>
                    </li>
                  </ul>
                </div>
                <div className="faded-logo">
                  <img src="/images/dashboard-faded-logo.png" />
                </div>
              </div>

              <div className="center-part">
                <div className="top d-flex justify-content-between align-items-center mb-5">
                  <div className="session-heading">
                    <h1>Dashboard</h1>
                  </div>

                  <div className="search">
                    <span>
                      {" "}
                      <i className="fa-solid fa-magnifying-glass"></i>
                    </span>
                    <input type="text" placeholder="Search something..." />
                  </div>

                  <div className="user d-flex align-items-center">
                    <div className="noti">
                      <button onClick={handleOpenModal}>
                        <img src="/images/notification-icon.png" />
                      </button>
                    </div>
                    <div className="text-end">
                      <h5>Your Name</h5>
                      <h6>User</h6>
                    </div>
                    <div className="user-logo">
                      <img src="/images/user-logo.png" />
                    </div>
                  </div>
                </div>

                <div className="middle d-flex justify-content-between">
                  <div className="d-flex  justify-content-between">
                    <div className="tkt-status">
                      <h4>Ticket Statuses</h4>
                    </div>
                    <div className="filter-submit-tkt">
                      <select>
                        <option selected>Filter</option>
                        <option>Filter1</option>
                        <option>Filter2</option>
                        <option>Filter3</option>
                      </select>
                      <Link className="dflt-button" href="/submit-ticket">
                        SUBMIT TICKET
                      </Link>
                    </div>
                  </div>

                  <div>
                    <div className="tkt-progress-box d-flex flex-wrap justify-content-between">
                      <div className="box d-flex align-items-center  justify-content-between">
                        <div>
                          <img src="/images/tkt-submission.png" />
                        </div>
                        <div>
                          <h5>025</h5>
                          <p>Ticket Submissions</p>
                        </div>
                      </div>

                      <div className="box d-flex align-items-center  justify-content-between">
                        <div>
                          <img src="/images/pending-tkt.png" />
                        </div>
                        <div>
                          <h5>007</h5>
                          <p>Pending Tickets</p>
                        </div>
                      </div>

                      <div className="box d-flex align-items-center  justify-content-between">
                        <div>
                          <img src="/images/inprogress-tkt.png" />
                        </div>
                        <div>
                          <h5>012</h5>
                          <p>Inprogress Tickets</p>
                        </div>
                      </div>

                      <div className="box d-flex align-items-center  justify-content-between">
                        <div>
                          <img src="/images/resolve-tkt.png" />
                        </div>
                        <div>
                          <h5>006</h5>
                          <p>Resolved Tickets</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="ticket-main">
                  <div className="row">
                    <div className="col-md-8">
                      <div className="ticket-table">
                        <div className="heightt">
                          <div className="top d-flex justify-content-between align-items-center">
                            <h5>Ticket History</h5>
                            <select>
                              <option selected>Weekly</option>
                              <option>Weekly</option>
                              <option>Weekly</option>
                              <option>Weekly</option>
                            </select>
                          </div>

                          <div className="tablee">
                            <table>
                              <thead>
                                <tr>
                                  <th>Ticket ID</th>
                                  <th>Reason</th>
                                  <th>Date</th>
                                  <th>Status</th>
                                  <th>Tracking</th>
                                </tr>
                              </thead>
                              <tbody>
                                <tr>
                                  <td>#00052</td>
                                  <td>Lorem Ipsum</td>
                                  <td>01 Jan 2023</td>
                                  <td class="pending">Pending</td>
                                  <td>SR0021P</td>
                                </tr>
                                <tr>
                                  <td>#051134</td>
                                  <td>Dolor Sit</td>
                                  <td>03 Jan 2023</td>
                                  <td class="resolved">Resolved</td>
                                  <td>PQ1132G</td>
                                </tr>
                                <tr>
                                  <td>#00052</td>
                                  <td>Lorem Ipsum</td>
                                  <td>01 Jan 2023</td>
                                  <td class="pending">Pending</td>
                                  <td>SR0021P</td>
                                </tr>
                                <tr>
                                  <td>#051134</td>
                                  <td>Dolor Sit</td>
                                  <td>03 Jan 2023</td>
                                  <td class="resolved">Resolved</td>
                                  <td>PQ1132G</td>
                                </tr>
                                <tr>
                                  <td>#00052</td>
                                  <td>Lorem Ipsum</td>
                                  <td>01 Jan 2023</td>
                                  <td class="pending">Pending</td>
                                  <td>SR0021P</td>
                                </tr>
                                <tr>
                                  <td>#051134</td>
                                  <td>Dolor Sit</td>
                                  <td>03 Jan 2023</td>
                                  <td class="resolved">Resolved</td>
                                  <td>PQ1132G</td>
                                </tr>
                                <tr>
                                  <td>#00052</td>
                                  <td>Lorem Ipsum</td>
                                  <td>01 Jan 2023</td>
                                  <td class="inprogress">Inprogress</td>
                                  <td>SR0021P</td>
                                </tr>
                                <tr>
                                  <td>#051134</td>
                                  <td>Dolor Sit</td>
                                  <td>03 Jan 2023</td>
                                  <td class="resolved">Resolved</td>
                                  <td>PQ1132G</td>
                                </tr>
                                <tr>
                                  <td>#00052</td>
                                  <td>Lorem Ipsum</td>
                                  <td>01 Jan 2023</td>
                                  <td class="inprogress">Inprogress</td>
                                  <td>SR0021P</td>
                                </tr>
                                <tr>
                                  <td>#00052</td>
                                  <td>Lorem Ipsum</td>
                                  <td>01 Jan 2023</td>
                                  <td class="inprogress">Inprogress</td>
                                  <td>SR0021P</td>
                                </tr>
                                <tr>
                                  <td>#051134</td>
                                  <td>Dolor Sit</td>
                                  <td>03 Jan 2023</td>
                                  <td class="resolved">Resolved</td>
                                  <td>PQ1132G</td>
                                </tr>
                                <tr>
                                  <td>#051134</td>
                                  <td>Dolor Sit</td>
                                  <td>03 Jan 2023</td>
                                  <td class="resolved">Resolved</td>
                                  <td>PQ1132G</td>
                                </tr>
                                <tr>
                                  <td>#051134</td>
                                  <td>Dolor Sit</td>
                                  <td>03 Jan 2023</td>
                                  <td class="resolved">Resolved</td>
                                  <td>PQ1132G</td>
                                </tr>
                                <tr>
                                  <td>#051134</td>
                                  <td>Dolor Sit</td>
                                  <td>03 Jan 2023</td>
                                  <td class="resolved">Resolved</td>
                                  <td>PQ1132G</td>
                                </tr>
                                <tr>
                                  <td>#051134</td>
                                  <td>Dolor Sit</td>
                                  <td>03 Jan 2023</td>
                                  <td class="resolved">Resolved</td>
                                  <td>PQ1132G</td>
                                </tr>
                                <tr>
                                  <td>#051134</td>
                                  <td>Dolor Sit</td>
                                  <td>03 Jan 2023</td>
                                  <td class="resolved">Resolved</td>
                                  <td>PQ1132G</td>
                                </tr>
                                <tr>
                                  <td>#051134</td>
                                  <td>Dolor Sit</td>
                                  <td>03 Jan 2023</td>
                                  <td class="resolved">Resolved</td>
                                  <td>PQ1132G</td>
                                </tr>
                                <tr>
                                  <td>#051134</td>
                                  <td>Dolor Sit</td>
                                  <td>03 Jan 2023</td>
                                  <td class="resolved">Resolved</td>
                                  <td>PQ1132G</td>
                                </tr>
                                <tr>
                                  <td>#051134</td>
                                  <td>Dolor Sit</td>
                                  <td>03 Jan 2023</td>
                                  <td class="resolved">Resolved</td>
                                  <td>PQ1132G</td>
                                </tr>
                                <tr>
                                  <td>#051134</td>
                                  <td>Dolor Sit</td>
                                  <td>03 Jan 2023</td>
                                  <td class="resolved">Resolved</td>
                                  <td>PQ1132G</td>
                                </tr>
                                <tr>
                                  <td>#00052</td>
                                  <td>Lorem Ipsum</td>
                                  <td>01 Jan 2023</td>
                                  <td class="inprogress">Inprogress</td>
                                  <td>SR0021P</td>
                                </tr>
                                <tr>
                                  <td>#00052</td>
                                  <td>Lorem Ipsum</td>
                                  <td>01 Jan 2023</td>
                                  <td class="inprogress">Inprogress</td>
                                  <td>SR0021P</td>
                                </tr>
                                <tr>
                                  <td>#00052</td>
                                  <td>Lorem Ipsum</td>
                                  <td>01 Jan 2023</td>
                                  <td class="inprogress">Inprogress</td>
                                  <td>SR0021P</td>
                                </tr>
                                <tr>
                                  <td>#00052</td>
                                  <td>Lorem Ipsum</td>
                                  <td>01 Jan 2023</td>
                                  <td class="inprogress">Inprogress</td>
                                  <td>SR0021P</td>
                                </tr>
                                <tr>
                                  <td>#00052</td>
                                  <td>Lorem Ipsum</td>
                                  <td>01 Jan 2023</td>
                                  <td class="inprogress">Inprogress</td>
                                  <td>SR0021P</td>
                                </tr>
                                <tr>
                                  <td>#00052</td>
                                  <td>Lorem Ipsum</td>
                                  <td>01 Jan 2023</td>
                                  <td class="inprogress">Inprogress</td>
                                  <td>SR0021P</td>
                                </tr>
                                <tr>
                                  <td>#00052</td>
                                  <td>Lorem Ipsum</td>
                                  <td>01 Jan 2023</td>
                                  <td class="inprogress">Inprogress</td>
                                  <td>SR0021P</td>
                                </tr>
                                <tr>
                                  <td>#00052</td>
                                  <td>Lorem Ipsum</td>
                                  <td>01 Jan 2023</td>
                                  <td class="inprogress">Inprogress</td>
                                  <td>SR0021P</td>
                                </tr>
                                <tr>
                                  <td>#00052</td>
                                  <td>Lorem Ipsum</td>
                                  <td>01 Jan 2023</td>
                                  <td class="inprogress">Inprogress</td>
                                  <td>SR0021P</td>
                                </tr>
                                <tr>
                                  <td>#00052</td>
                                  <td>Lorem Ipsum</td>
                                  <td>01 Jan 2023</td>
                                  <td class="inprogress">Inprogress</td>
                                  <td>SR0021P</td>
                                </tr>
                                <tr>
                                  <td>#00052</td>
                                  <td>Lorem Ipsum</td>
                                  <td>01 Jan 2023</td>
                                  <td class="inprogress">Inprogress</td>
                                  <td>SR0021P</td>
                                </tr>
                              </tbody>
                            </table>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="col-md-4">
                      <div className="circular-chartt">
                        <div className="top d-flex justify-content-between align-items-center">
                          <h5>Ticket Status</h5>
                          <h6>View Details</h6>
                        </div>
                        <div className="chart-container">
                          <img className="w-100 mt-3" src="/images/donut.png" />
                        </div>
                      </div>

                      <div className="paid-rent">
                        <div className="top d-flex justify-content-between align-items-center">
                          <h5>Paid Rent</h5>
                          <h6>View Details</h6>
                        </div>
                        <div className="paid-rent-conatiner">
                          <ul>
                            <li>
                              <div>
                                <strong>Date</strong>
                              </div>
                            </li>

                            <li>
                              <div>
                                <p>01 Dec 2024</p>
                              </div>
                            </li>

                            <li>
                              <div>
                                <p>03 Nov 2024</p>
                              </div>
                            </li>
                          </ul>

                          <ul>
                            <li>
                              <div>
                                <strong>Name</strong>
                              </div>
                            </li>

                            <li>
                              <div>
                                <p>Robert</p>
                              </div>
                            </li>

                            <li>
                              <div>
                                <p>Robert</p>
                              </div>
                            </li>
                          </ul>

                          <ul>
                            <li>
                              <div>
                                <strong>Amount</strong>
                              </div>
                            </li>

                            <li>
                              <div>
                                <p>$150.82</p>
                              </div>
                            </li>

                            <li>
                              <div>
                                <p>$150.82</p>
                              </div>
                            </li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <div className="footerr copy-right text-center">
          <p>Copyright 2024 Paramount Management Group</p>
        </div>
        {showModal && (
          <div
            className="modal fade show d-block"
            tabIndex="-1"
            role="dialog"
            style={{ backgroundColor: "rgba(0,0,0,0.5)" }}
          >
            <div className="modal-dialog" role="document">
              <div className="modal-content">
                <div className="modal-header">
                  <h5 className="modal-title">No New Notification</h5>
                  <button
                    type="button"
                    className="btn-close"
                    onClick={handleCloseModal}
                  ></button>
                </div>
                <div className="modal-body"></div>
                <div className="modal-footer">
                  <button
                    type="button"
                    className="btn btn-secondary"
                    onClick={handleCloseModal}
                  >
                    Close
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </>
  );
}
