import "@/app/globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import '@fortawesome/fontawesome-free/css/all.min.css';
import { Toaster } from 'react-hot-toast';
import { cookies } from "next/headers";
import axios from "@/utils/axios";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
async function getData() {
    return cookies().get('token').value
}
export default async function RootLayout({ children }) {
    const token = await getData()
    console.log('called here')
    if(token){
        axios.defaults.headers['Authorization'] = `Bearer ${token}`;
    }
    return (
        <html lang="en">
            <body>
                <Toaster position="top-right" reverseOrder={false} />
                {children}
            </body>
        </html>
    );
}
