import Head from "next/head";

import Link from "next/link";
import Image from "next/image";
import Header from "../../components/header";
import Footer from "../../components/Footer";

export default function BlogDetail() {
  return (
    <>
      <Head>
        <title>Paramount Management Group</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="scroll-content">
        <Header />

        <section className="inner-banner blogs-banner">
          <div className="container">
            <div className="content">
              <h1 data-aos="fade-up" className="main-heading">
                <span>BLOG</span>
              </h1>
            </div>
          </div>
        </section>

        <section className="blog-detail-section-two">
          <div className="container">
            <div className="content">
              <div className="title text-center">
              <h6 data-aos="fade-up" className="mini-heading">Paramount Management Group</h6>
                <h2 data-aos="fade-up" className="sub-heading">
                  Blog <span>Title Heading</span>
                </h2>
                <p data-aos="fade-up" className="paragraph">
                  Stay informed with industry insights and updates from PMG.
                  Discover why businesses choose Bushnell for professional
                  growth.
                </p>
              </div>

              <div className="row align-items-center mb-6">
                <div className="col-md-6">
                  <div className="img" data-aos="zoom-in">
                    <img src="/images/blog-detail-section-img.png" />
                  </div>
                </div>

                <div className="col-md-6">
                  <div className="text">
                    <p data-aos="fade-up" className="paragraph">
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                      sed do eiusmod tempor incididunt ut labore et dolore magna
                      aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                      ullamco laboris nisi ut aliquip ex ea commodo consequat.
                    </p>

                    <p data-aos="fade-up" className="paragraph">
                      Duis aute irure dolor in reprehenderit in voluptate velit
                      esse cillum dolore eu fugiat nulla pariatur. Excepteur
                      sint occaecat cupidatat non proident, sunt in culpa qui
                      officia.
                    </p>

                    <p data-aos="fade-up" className="paragraph">
                      Deserunt mollit anim id est laborum non proident, sunt in
                      culpa qui officia deserunt mollit anim id est laborumnon
                      proident, sunt in laborumnon proident, sunt in culpa qui
                      officia deserunt mollit anim id est laborum.
                    </p>
                  </div>
                </div>
              </div>

              <p data-aos="fade-up" className="paragraph">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation ullamco laboris
                nisi ut aliquip ex ea commodo consequat sunt in culpa qui
                officia deserunt mollit anim id est laborumnon proident, sunt in
                culpa qui officia deserunt mollit anim id est laborum.
              </p>
              <p data-aos="fade-up" className="paragraph">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation ullamco laboris
                nisi ut aliquip ex ea commodo consequat sunt in culpa qui
                officia deserunt mollit anim id est laborumnon proident, sunt in
                culpa qui officia deserunt mollit anim id est laborum.
              </p>
            </div>
          </div>
        </section>

        <section className="home home-section-seven">
          <div className="container">
            <div className="title text-center">
              <h6 data-aos="fade-up" className="mini-heading">Paramount Management Group</h6>
              <h1 data-aos="fade-up" className="main-heading">
                Stay In <span>Touch</span>
              </h1>
              <p data-aos="fade-up" className="paragraph">
                It is a long established fact that a reader will be distracted
                by the readable content of a page when looking at its layout the
                point of using Lorem Ipsum.
              </p>
            </div>

            <div className="content">
              <div className="row justify-content-center">
                <div className="col-md-8">
                  <div className="row">
                    <div className="col-md-6">
                      <input type="text" placeholder="First Name" />
                    </div>

                    <div className="col-md-6">
                      <input type="text" placeholder="Last Name" />
                    </div>

                    <div className="col-md-6">
                      <input type="text" placeholder="First Name" />
                    </div>

                    <div className="col-md-6">
                      <input type="text" placeholder="Last Name" />
                    </div>

                    <div className="col-md-12">
                      <textarea placeholder="Message"></textarea>
                    </div>
                  </div>
                  <button>Send Message</button>
                </div>
              </div>
            </div>
          </div>
        </section>

        <Footer />
      </div>
    </>
  );
}
