import Head from "next/head";

import Link from "next/link";
import Image from "next/image";
import Header from "../../components/header";
import Footer from "../../components/Footer";

export default function AboutUs() {
  return (
    <>
      <Head>
        <title>Paramount Management Group</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="scroll-content">
        <Header />

        <section className="inner-banner about-banner">
          <div className="container">
            <div className="content">
              <h1 className="main-heading" data-aos="fade-up">
                <span>ABOUT US</span>
              </h1>
            </div>
          </div>
        </section>

        <section className="home home-section-four about-section-two">
          <div className="container">
            <div className="row align-items-center mb-5">
              <div className="col-md-6">
                <div data-aos="zoom-in" className="img text-start">
                  <img
                    src="/images/home-sec-four-img.png"
                    alt="home-sec-four-img"
                  />
                </div>
              </div>
              <div className="col-md-6">
                <div className="text">
                  <h6 className="mini-heading" data-aos="fade-up">Welcome to</h6>
                  <h1 className="main-heading" data-aos="fade-up">
                    <span> Paramount</span> Management Group LLC
                  </h1>
                  <p data-aos="fade-up" className="paragraph yellowish">
                  Since our inception in 2005 in Bushnell, Florida, we've been redefining what commercial property management can be. Our expert <b>property management solutions</b> transform buildings into dynamic spaces where businesses flourish.
                  </p>
                  <h5 className="sub-text">Why Paramount? </h5>
                  <p data-aos="fade-up" className="paragraph">
                  Imagine a workspace that doesn’t just house your business—it propels it to new heights. That’s the power of our <b>property management solutions.</b> Our properties go beyond mere locations; they are launchpads for your entrepreneurial ambitions.
                  </p>
                  <h5 className="sub-text">Our Mission</h5>
                  <p data-aos="fade-up" className="paragraph">
                  We’re committed to excellence, ensuring your workspace is more than functional—it's phenomenal. With top-tier <b>property management solutions</b> and meticulous attention to maintenance, we manage the details so you can focus on your business goals.
                  </p>
                  <h5 className="sub-text">Vision for the Future</h5>
                  <p data-aos="fade-up" className="paragraph">As we expand our portfolio, your opportunities grow. We’re raising the bar in property management solutions, ensuring each property is perfectly poised to support its tenants' success</p>
                </div>
              </div>
            </div>
            <div className="row">
              <h5 className="sub-text">Our Core Values</h5>
              <div className="col-md-6">
                <ul>
                  <li>
                    <b>Excellence in Service:</b> Our commitment to unparalleled service quality sets the standard in property management, consistently exceeding expectations.
                  </li>
                  <li>
                    <b>Tenant Success</b> Your growth is our priority. Through our <b>tenants portal,</b>
                    we provide prime spaces in key locations, setting the stage for your success.
                  </li>
                  <li>
                    <b>Integrity and Transparency:</b> We operate with honesty and clarity, building trust through every interaction.
                  </li>
                  
                </ul>
              </div>

              <div className="col-md-6">
               
              <ul>
              <li> <b>Community Focus:</b> We do more than manage properties; we cultivate thriving business ecosystems that enrich communities.</li>
                  <li> <b>Sustainability:</b> We're committed to eco-friendly practices that enhance property value and protect our environment </li>
                  <li> <b>Continuous Improvement:</b>  Innovation is at the heart of our property management strategies, keeping us ahead in the industry.
                  </li>
              </ul>
               
              </div>
              <p className="paragraph mt-4">Interested in how we can enhance your business environment? Reach out through our
                    <b>tenants portal </b> or learn about our comprehensive <b> tenant screening services</b> . At Paramount Management Group, we don’t just support your business—we empower it for future triumphs.
                  </p>
            </div>
          </div>
        </section>

        <section className="home home-section-seven">
          <div className="container">
            <div className="title text-center">
              <h6 className="mini-heading" data-aos="fade-up">Paramount Management Group</h6>
              <h1 className="main-heading" data-aos="fade-up">
                Stay In <span>Touch</span>
              </h1>
              <p data-aos="fade-up" className="paragraph">
                It is a long established fact that a reader will be distracted
                by the readable content of a page when looking at its layout the
                point of using Lorem Ipsum.
              </p>
            </div>

            <div className="content">
              <div className="row justify-content-center">
                <div className="col-md-8">
                  <div className="row">
                    <div className="col-md-6">
                      <input type="text" placeholder="First Name" />
                    </div>

                    <div className="col-md-6">
                      <input type="text" placeholder="Last Name" />
                    </div>

                    <div className="col-md-6">
                      <input type="text" placeholder="First Name" />
                    </div>

                    <div className="col-md-6">
                      <input type="text" placeholder="Last Name" />
                    </div>

                    <div className="col-md-12">
                      <textarea placeholder="Message"></textarea>
                    </div>
                  </div>
                  <button>Send Message</button>
                </div>
              </div>
            </div>
          </div>
        </section>

        <Footer />
      </div>
    </>
  );
}
