"use client";  // Ensure it's a client component

import { useEffect } from "react";

import "bootstrap/dist/css/bootstrap.min.css";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "owl.carousel/dist/assets/owl.carousel.min.css";
import "owl.carousel/dist/assets/owl.theme.default.min.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import { Toaster } from 'react-hot-toast';
import "../styles/globals.css";
// import "../styles/responsive.css";
// import { useEffect } from "react";
import AOS from "aos";
import "aos/dist/aos.css";


// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({ children }) {
  useEffect(() => {
    AOS.init({
      duration: 1000, // Animation duration
      once: true, // Whether animation should run only once
    });
  }, []);
  return (
    <html lang="en">
      <body>
      <Toaster position="top-right" reverseOrder={false} />
        {children}
        </body>
    </html>
  )
}
