"use client";
import Head from "next/head";

import Link from "next/link";
import Image from "next/image";
import Header from "../components/header";
import Footer from "../components/Footer";
import handleContactUs from "../auth/api/contactUsHelper";
import { useEffect, useState } from "react";

export default function Service() {
  const [formData, setFormData] = useState({
    first_name: "",
    last_name: "",
    email: "",
    phone: "",
    message: "",
  });

  const handleInputChange = (field, value) => {
    setFormData({
      ...formData,
      [field]: value,
    });
  };

  return (
    <>
      <Head>
        <title>Paramount Management Group</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="scroll-content">
        <Header />

        <section className="inner-banner blogs-banner service-banner">
          <div className="container">
            <div className="content">
              <h1 data-aos="fade-up" className="main-heading">
                <span>SERVICES</span>
              </h1>
            </div>
          </div>
        </section>

        <section className="home home-section-three services-section-two">
          <div className="container">
            <div className="title text-center">
              <h6 data-aos="fade-up" className="mini-heading">
                Paramount Management Group
              </h6>
              <h2 data-aos="fade-up" className="sub-heading">
                Our <span>Services</span>
              </h2>
              <p data-aos="fade-up" className="paragraph">
                Paramount Management Group (PMG) offers a range of personalized
                services designed to enhance tenant satisfaction and ensure the
                smooth operation of their leased spaces. These services include:
              </p>
            </div>

            <div className="row">
              <div className="col-md-6">
                <div className="inner">
                  <img
                    src="/images/home-sec-three-card-img1.png"
                    alt="home-sec-three-card-img1"
                  />
                  <h5 className="sub-text" data-aos="zoom-in">
                    Responsive Maintenance & Repairs
                  </h5>
                  <p data-aos="fade-up" className="paragraph">
                    Get reliable 24/7 property maintenance, proactive care, and
                    quick emergency repairs to ensure smooth operations and
                    professional spaces where businesses thrive effortlessly.
                  </p>
                  <Link href="">
                    <i className="fa-solid fa-arrow-right"></i>
                  </Link>
                </div>
              </div>

              <div className="col-md-6">
                <div className="inner">
                  <img
                    src="/images/home-sec-three-card-img2.png"
                    alt="home-sec-three-card-img2"
                  />
                  <h5 className="sub-text" data-aos="zoom-in">
                    Property Customization
                  </h5>
                  <p data-aos="fade-up" className="paragraph">
                    Customize leased spaces to fit your unique business needs.
                    PMG offers tailored solutions, seamless upgrades, and
                    collaborative processes to create functional, compliant
                    workspaces.
                  </p>
                  <Link href="">
                    <i className="fa-solid fa-arrow-right"></i>
                  </Link>
                </div>
              </div>

              <div className="col-md-6">
                <div className="inner">
                  <img
                    src="/images/home-sec-three-card-img3.png"
                    alt="home-sec-three-card-img3"
                  />
                  <h5 className="sub-text" data-aos="zoom-in">
                    Clear Communication
                  </h5>
                  <p data-aos="fade-up" className="paragraph">
                    Stay informed with transparent updates, responsive
                    communication, and efficient issue resolution. PMG
                    prioritizes tenant satisfaction through clear processes and
                    collaborative management strategies.
                  </p>
                  <Link href="">
                    <i className="fa-solid fa-arrow-right"></i>
                  </Link>
                </div>
              </div>

              <div className="col-md-6">
                <div className="inner">
                  <img
                    src="/images/home-sec-three-card-img4.png"
                    alt="home-sec-three-card-img4"
                  />
                  <h5 className="sub-text" data-aos="zoom-in">
                    Tenant Portal
                  </h5>
                  <p data-aos="fade-up" className="paragraph">
                    Simplify your property management experience. Access lease
                    details, submit service requests, and track payments with
                    PMG’s efficient and user-friendly online tenant portal.
                  </p>
                  <Link href="">
                    <i className="fa-solid fa-arrow-right"></i>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="home home-section-seven">
          <div className="container">
            <div className="title text-center">
              <h6 data-aos="fade-up" className="mini-heading">
                Paramount Management Group
              </h6>
              <h1 data-aos="fade-up" className="main-heading">
                Stay In <span>Touch</span>
              </h1>
              <p data-aos="fade-up" className="paragraph">
                It is a long established fact that a reader will be distracted
                by the readable content of a page when looking at its layout the
                point of using Lorem Ipsum.
              </p>
            </div>

            <div className="content">
              <div className="row justify-content-center">
                <div className="col-md-8">
                  <div className="row">
                    <div className="col-md-6">
                      <input
                    type="text"
                    placeholder="First Name *"
                    value={formData.first_name}
                    onChange={(e) => handleInputChange("first_name", e.target.value)}
                  />
                    </div>

                    <div className="col-md-6">
                    <input
                    type="text"
                    placeholder="Last Name *"
                    value={formData.last_name}
                    onChange={(e) => handleInputChange("last_name", e.target.value)}
                  />
                    </div>

                    <div className="col-md-6">
                    <input
                    type="email"
                    placeholder="Email Address *"
                    value={formData.email}
                    onChange={(e) => handleInputChange("email", e.target.value)}
                  />
                    </div>

                    <div className="col-md-6">
                    <input
                    type="tel"
                    placeholder="Phone Number *"
                    value={formData.phone}
                    onChange={(e) => handleInputChange("phone", e.target.value)}
                  />
                    </div>

                    <div className="col-md-12">
                    <textarea
                    placeholder="Message Here..."
                    value={formData.message}
                    onChange={(e) => handleInputChange("message", e.target.value)}
                  ></textarea>
                    </div>
                  </div>
                  <button onClick={() => handleContactUs(formData, setFormData)}>Send Message</button>
                </div>
              </div>
            </div>
          </div>
        </section>

        <Footer />
      </div>
    </>
  );
}
