"use client";
import Head from "next/head";
import React, { useState } from "react";
import Link from "next/link";
import Image from "next/image";
import Header from "../components/header";
import Footer from "../components/Footer";
import Sidebar from "../components/Sidebar";
import DashboardHeader from "../components/DashboardHeader";

export default function Messages() {
  const [showModal, setShowModal] = useState(false);
  const [isActive, setIsActive] = useState(true);

  const handleOpenModal = () => setShowModal(true);
  const handleCloseModal = () => setShowModal(false);

  // CHAT SCREEN
  const [messages, setMessages] = useState([
    { sender: "You", text: "Hi!" },
    { sender: "Other", text: "Hello! How are you?" },
    { sender: "You", text: "I am good, thanks! What about you?" },
    { sender: "Other", text: "I am doing great as well!" },
  ]);
  const [input, setInput] = useState("");

  const sendMessage = () => {
    if (input.trim() !== "") {
      setMessages([...messages, { sender: "You", text: input }]);
      setInput("");
    }
  };
  return (
    <>
      <Head>
        <title>Paramount Management Group</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="scroll-content">
        <section className="dashboard-main submit-ticket messages">
          <div className="container-fluid">
            <div className="dashboard-content d-flex">
              <div className="left-bar">
                <div className="top-logo">
                  <img src="/images/dashboard-logo.png" />
                </div>
<Sidebar />
                <div className="faded-logo">
                  <img src="/images/dashboard-faded-logo.png" />
                </div>
              </div>

              <div className="center-part">
               <DashboardHeader />

                <div className="middle d-flex justify-content-between">
                  <div className="tkt-status">
                    <h4>Messages</h4>
                  </div>
                  <div className="submit-ticket-main chat-area">
                    <div className="chat-window">
                      <div className="messages">
                        {messages.map((msg, index) => (
                          <div
                            key={index}
                            className={`message ${
                              msg.sender === "You" ? "sent" : "received"
                            }`}
                          >
                            <span>{msg.text}</span>
                          </div>
                        ))}
                      </div>
                      <div className="input-bar d-flex">
                        <input
                          type="text"
                          value={input}
                          onChange={(e) => setInput(e.target.value)}
                          placeholder="Type a message..."
                        />
                        <button onClick={sendMessage}>Send</button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <div className="footerr copy-right text-center">
          <p>Copyright 2024 Paramount Management Group</p>
        </div>
        
      </div>
    </>
  );
}
