import Head from "next/head";

import Link from "next/link";
import Image from "next/image";
import Header from "../../components/header";
import Footer from "../../components/Footer";

export default function ContactUs() {
  return (
    <>
      <Head>
        <title>Paramount Management Group</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="scroll-content">
        <Header />

        <section className="inner-banner blogs-banner contact-banner">
          <div className="container">
            <div className="content">
              <h1 data-aos="fade-up" className="main-heading">
                <span>PROPERTIES</span>
              </h1>
            </div>
          </div>
        </section>

        <section className="home home-section-two properties-section-two">
          <div className="container">
            <div className="text-center title">
              <h6 data-aos="fade-up" className="mini-heading">
                Paramount Management Group
              </h6>
              <h1 data-aos="fade-up" className="main-heading">
              Find  <span>Your Perfect Space</span>
              </h1>
              <p className="paragraph">
              Looking for an office that matches your ambition? Our featured office spaces are designed to help your business shine. Whether you're starting up or scaling up, discover the ideal backdrop for your next big move. 
              </p>
            </div>

            <div className="row">
              <div className="col-md-6">
                <div className="inner" data-aos="zoom-in">
                  <div className="img">
                    <img
                      src="/images/home-sec-two-card-img1.png"
                      alt="home-sec-two-card-img1"
                    />
                  </div>
                  <div className="text">
                    <h5 className="sub-text">
                      1st Floor, Ste 103 <br></br>Bushnell Plaza | 138 Bushnell
                      Plz
                    </h5>
                    <p className="paragraph">
                      247 - 1,037 SF of Office Space Available in Bushnell, FL
                      33513
                    </p>
                    <div className="d-flex">
                      <div className="black-bg">
                        <h5 className="sub-text">
                          <Link href="/property-detail-one">
                            <span>View in Detail</span>
                          </Link>
                        </h5>
                      </div>
                      {/* <div>
                        <ul>
                          <li>790 SF | 1-5 Years | $22.78 /SF/YR</li>

                          <li>Office | Full Build-Out | Available Property</li>
                        </ul>
                      </div> */}
                    </div>
                  </div>
                </div>
              </div>

              <div className="col-md-6">
                <div className="inner" data-aos="zoom-in">
                  <div className="img">
                    <img
                      src="/images/home-sec-two-card-img2.png"
                      alt="home-sec-two-card-img2"
                    />
                  </div>
                  <div className="text">
                    <h5 className="sub-text">
                      2nd Floor, Ste 201 <br></br>Bushnell Plaza | 138 Bushnell
                      Plz
                    </h5>
                    <p className="paragraph">
                      247 - 1,037 SF of Office Space Available in Bushnell, FL
                      33513
                    </p>
                    <div className="d-flex">
                      <div className="black-bg">
                        <h5 className="sub-text">
                          <Link href="/property-detail-two">
                            <span>View in Detail</span>
                          </Link>
                        </h5>
                      </div>
                      {/* <div>
                        <ul>
                          <li>247 SF | 1-5 Years | $29.16 /SF/YR</li>

                          <li>Office | Full Build-Out | Available Property</li>
                        </ul>
                      </div> */}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="home home-section-seven">
          <div className="container">
            <div className="title text-center">
              <h6 data-aos="fade-up" className="mini-heading">
                Paramount Management Group
              </h6>
              <h1 data-aos="fade-up" className="main-heading">
                Stay In <span>Touch</span>
              </h1>
              <p data-aos="fade-up" className="paragraph">
              We understand that finding the right commercial space is more than just finding an address. It's about finding a location that inspires, a space that supports your team's productivity, and a partner that understands your unique business needs.
              </p>
            </div>

            <div className="content">
              <div className="row justify-content-center">
                <div className="col-md-8">
                  <div className="row">
                    <div className="col-md-6">
                      <input type="text" placeholder="First Name" />
                    </div>

                    <div className="col-md-6">
                      <input type="text" placeholder="Last Name" />
                    </div>

                    <div className="col-md-6">
                      <input type="text" placeholder="First Name" />
                    </div>

                    <div className="col-md-6">
                      <input type="text" placeholder="Last Name" />
                    </div>

                    <div className="col-md-12">
                      <textarea placeholder="Message"></textarea>
                    </div>
                  </div>
                  <button>Send Message</button>
                </div>
              </div>
            </div>
          </div>
        </section>
        <Footer />
      </div>
    </>
  );
}
